"""
Django settings for CarParking project.

Generated by 'django-admin startproject' using Django 5.2.8.
"""

from pathlib import Path
from django.contrib.messages import constants as messages
from decouple import config
import cloudinary
import cloudinary.uploader
import cloudinary.api

# --- 1. BASE DIRECTORY ---
BASE_DIR = Path(__file__).resolve().parent.parent

# --- 2. SECURITY ---
SECRET_KEY = config('SECRET_KEY', default='unsafe-secret-key-for-dev')
DEBUG = config('DEBUG', default=True, cast=bool)

# FIXED: Provide default hosts for local development
ALLOWED_HOSTS = config(
    'ALLOWED_HOSTS',
    default='127.0.0.1,localhost,testserver',
    cast=lambda v: [s.strip() for s in v.split(',')]
)

# --- 3. APPLICATION DEFINITION ---
INSTALLED_APPS = [
    # Default Django Apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Project Apps
    'CarParking.apps.CarParkingConfig',
    'accounts.apps.AccountsConfig',
    'parking.apps.ParkingConfig',
    'widget_tweaks',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'CarParking.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'Templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # Site-wide settings (SITE_NAME and contact info)
                'CarParking.context_processors.site_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'CarParking.wsgi.application'

# --- 4. DATABASE ---
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# --- 5. PASSWORD VALIDATION ---
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# --- 6. INTERNATIONALIZATION ---
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# --- 7. STATIC FILES ---
STATIC_URL = 'static/'
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# Serve the project-level `assets/` folder via Django staticfiles during development
STATICFILES_DIRS = [
    BASE_DIR / 'assets',
]

# --- 8. CUSTOM SETTINGS ---

# Custom User Model
AUTH_USER_MODEL = 'CarParking.User'

# Explicit authentication backends: keep default ModelBackend for predictable behavior
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

# Friendly site name used in templates and emails
SITE_NAME = config('SITE_NAME', default='SmartPark')

# Version string appended to asset URLs to help with cache-busting during development.
# Increment `ASSET_VERSION` or set in your environment to force browsers to reload assets.
ASSET_VERSION = config('ASSET_VERSION', default='1')

# Authentication Redirects
LOGIN_REDIRECT_URL = 'driver_dashboard'
LOGOUT_REDIRECT_URL = 'login'

# Message tags for Bootstrap/HTML
MESSAGE_TAGS = {
    messages.DEBUG: 'debug',
    messages.INFO: 'info',
    messages.SUCCESS: 'success',
    messages.WARNING: 'warning',
    messages.ERROR: 'error',
}

# --- 9. CLOUDINARY CONFIGURATION ---
cloudinary.config(
    cloud_name=config('CLOUDINARY_CLOUD_NAME', default=''),
    api_key=config('CLOUDINARY_API_KEY', default=''),
    api_secret=config('CLOUDINARY_API_SECRET', default=''),
    secure=True
)
import os
try:
    # `python-dotenv` is optional for environments that already provide env vars.
    # Use a safe fallback so missing the package doesn't break `manage.py` tools.
    from dotenv import load_dotenv
    load_dotenv()
except Exception:
    # If dotenv isn't installed, continue silently (env vars should be provided externally).
    def load_dotenv():
        return None
    # no-op called to keep behavior consistent
    load_dotenv()

# Environment configs for email sending. Provide sensible defaults for development:
# - When DEBUG=True and no EMAIL_BACKEND is provided, use the console backend so mails
#   appear in the runserver console during development.
# - In production, set EMAIL_BACKEND, EMAIL_HOST, EMAIL_PORT, EMAIL_HOST_USER, EMAIL_HOST_PASSWORD, DEFAULT_FROM_EMAIL in your environment.
env_email_backend = os.getenv('EMAIL_BACKEND')
if env_email_backend:
    EMAIL_BACKEND = env_email_backend
    # If a file-based backend is explicitly provided via env, allow
    # overriding FILE_PATH via env too so one-off commands can write files.
    if 'filebased' in EMAIL_BACKEND:
        env_file_path = os.getenv('EMAIL_FILE_PATH')
        if env_file_path:
            EMAIL_FILE_PATH = env_file_path
        else:
            EMAIL_FILE_PATH = BASE_DIR / 'sent_emails'
else:
    # Default to a file-based backend during development so outgoing
    # emails (including password-reset links) are written to disk
    # and easy to inspect. In production set EMAIL_BACKEND env var.
    if DEBUG:
        EMAIL_BACKEND = 'django.core.mail.backends.filebased.EmailBackend'
        EMAIL_FILE_PATH = BASE_DIR / 'sent_emails'
    else:
        EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_HOST = os.getenv('EMAIL_HOST', 'localhost')
# Cast port to int if provided, otherwise pick a sensible default (1025 for dev, 587 for prod)
email_port_env = os.getenv('EMAIL_PORT')
if email_port_env:
    try:
        EMAIL_PORT = int(email_port_env)
    except ValueError:
        EMAIL_PORT = 587
else:
    EMAIL_PORT = 1025 if DEBUG else 587

EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True' if DEBUG else 'True').lower() in ('1', 'true', 'yes')
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@localhost')
# --- 10. M-PESA SETTINGS (for STK Push) ---
# These can be set in the environment or .env for production. Default to simulate mode for local dev.
MPESA_CONSUMER_KEY = config('MPESA_CONSUMER_KEY', default='')
MPESA_CONSUMER_SECRET = config('MPESA_CONSUMER_SECRET', default='')
MPESA_SHORTCODE = config('MPESA_SHORTCODE', default='')
MPESA_PASSKEY = config('MPESA_PASSKEY', default='')
# When True, STK push calls are simulated and payment confirmation is scheduled locally.
MPESA_SIMULATE = config('MPESA_SIMULATE', default=True, cast=bool)
# Optional: override API base (use sandbox by default)
# Optional: override API base (use sandbox by default). Support legacy env `BASE_URL`.
MPESA_API_BASE = config('MPESA_API_BASE', default=config('BASE_URL', default='https://sandbox.safaricom.co.ke'))
# Callback URL that Safaricom will POST to for transaction results (configure in sandbox)
# Support legacy env `CALLBACK_URL` used in some deployments
MPESA_CALLBACK_URL = config('MPESA_CALLBACK_URL', default=config('CALLBACK_URL', default='https://yourdomain.example.com/parking/payment/callback/'))

# Optional secret to validate incoming MPesa callbacks (set in .env and in the Daraja sandbox if supported)
MPESA_CALLBACK_SECRET = config('MPESA_CALLBACK_SECRET', default='')

# CSRF: trusted origins for deployments where the Host/Origin may include
# an explicit scheme or different hostname (common in Docker, tunnelling,
# or when using an IP address). Allow overriding via env var.
CSRF_TRUSTED_ORIGINS = config(
    'CSRF_TRUSTED_ORIGINS',
    default='http://127.0.0.1:8000,http://localhost:8000',
    cast=lambda v: [s.strip() for s in v.split(',') if s.strip()]
)

# Expire sessions on browser close so users are logged out when they close the browser
SESSION_EXPIRE_AT_BROWSER_CLOSE = config('SESSION_EXPIRE_AT_BROWSER_CLOSE', default=True, cast=bool)