# Generated by Django 5.2.8 on 2025-12-10 14:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(blank=True, default='homepage', max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='parkingslot',
            options={'ordering': ['slot_id']},
        ),
        migrations.AlterField(
            model_name='booking',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='parkingslot',
            name='level',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='parkingslot',
            name='pricing_category',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Premium', 'Premium'), ('VIP', 'VIP')], default='Regular', max_length=20),
        ),
        migrations.AlterField(
            model_name='parkingslot',
            name='slot_id',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
