# Generated by Django 5.2.8 on 2025-12-12 16:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_subscription_alter_parkingslot_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Regular', 'Regular'), ('Premium', 'Premium'), ('VIP', 'VIP')], max_length=20, unique=True)),
                ('rate', models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=8)),
            ],
            options={
                'ordering': ['category'],
            },
        ),
    ]
