# Generated by Django 5.2.8 on 2025-12-07 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarParking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSlot',
            fields=[
                ('slot_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('slot_name', models.CharField(help_text='e.g., Level 1, Spot 101', max_length=100)),
                ('pricing_category', models.CharField(choices=[('STANDARD', 'Standard Rate'), ('PREMIUM', 'Premium Rate'), ('DISABLED', 'Disabled Spot Rate')], default='STANDARD', max_length=10)),
                ('is_occupied', models.BooleanField(default=False, help_text='True if currently reserved or occupied.')),
                ('level', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Parking Slot',
                'verbose_name_plural': 'Parking Slots',
                'ordering': ['slot_id'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('total_fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Payment Pending'), ('PAID', 'Payment Confirmed'), ('FAILED', 'Payment Failed'), ('CANCELLED', 'Cancelled/Refunded')], default='PENDING', max_length=10)),
                ('mpesa_receipt_no', models.CharField(blank=True, help_text='The unique M-Pesa transaction reference number (filled on payment success).', max_length=30, null=True, unique=True)),
                ('checkout_request_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(help_text='The user who made the reservation.', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('slot', models.ForeignKey(help_text='The parking spot reserved.', on_delete=django.db.models.deletion.RESTRICT, related_name='reservations', to='CarParking.parkingslot')),
            ],
        ),
    ]
