# Generated by Django 5.2.8 on 2025-12-08 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarParking', '0002_parkingslot_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='slot',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_driver',
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True, verbose_name='M-Pesa Phone Number'),
        ),
        migrations.DeleteModel(
            name='ParkingSlot',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
