# Generated by Django 5.2.8 on 2025-12-11 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarParking', '0003_remove_booking_slot_remove_booking_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='SmartPark', max_length=200)),
                ('email', models.EmailField(blank=True, default='info@smartpark.example', max_length=254)),
                ('phone', models.CharField(blank=True, default='+1-555-0100', max_length=50)),
                ('address', models.TextField(blank=True, default='123 Parking Lane, YourCity')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Information',
                'verbose_name_plural': 'Contact Information',
            },
        ),
    ]
